[atcoder]
submit_via_binary = false
use_cross = false
binary_column = 80
update_interval = 1000
strip_path = "strip"

[profile]
target = "x86_64-unknown-linux-musl"

[profile.release]
lto = true
panic = 'abort'

[dependencies]
proconio = "*"

[project]
template = """
use proconio::input;

fn main() {
    input! { _a: usize, _b: usize }
}
"""
